=== anastasia-zhukova/uCDCR/NP4E-prep/NP4E/peru/markables/markables.dtd
<!ELEMENT markables (markable*)>
<!ELEMENT markable EMPTY>
<!ATTLIST markable id ID #REQUIRED>
<!ATTLIST markable span CDATA #REQUIRED>
<!ATTLIST markable member CDATA #IMPLIED>
<!ATTLIST markable pointer IDREF #IMPLIED>

=== anastasia-zhukova/uCDCR/NP4E-prep/NP4E/tajikistan/markables/375068newsML_section_level.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE markables SYSTEM "markables.dtd">
<markables xmlns="www.eml.org/NameSpaces/section">
<markable id="markable_2" span="word_1..word_9" mmax_level="section"/>
<markable id="markable_5" span="word_10..word_18" mmax_level="section"/>
<markable id="markable_7" span="word_19..word_20" mmax_level="section"/>
<markable id="markable_9" span="word_21..word_56" mmax_level="section"/>
<markable id="markable_11" span="word_57..word_87" mmax_level="section"/>
<markable id="markable_13" span="word_88..word_129" mmax_level="section"/>
<markable id="markable_16" span="word_130..word_155" mmax_level="section"/>
<markable id="markable_18" span="word_156..word_185" mmax_level="section"/>
<markable id="markable_21" span="word_186..word_231" mmax_level="section"/>
<markable id="markable_23" span="word_232..word_266" mmax_level="section"/>
<markable id="markable_25" span="word_267..word_297" mmax_level="section"/>
<markable id="markable_27" span="word_298..word_322" mmax_level="section"/>
<markable id="markable_29" span="word_323..word_345" mmax_level="section"/>
<markable id="markable_31" span="word_346..word_368" mmax_level="section"/>
<markable id="markable_33" span="word_369..word_413" mmax_level="section"/>
<markable id="markable_36" span="word_414..word_450" mmax_level="section"/>
<markable id="markable_38" span="word_451..word_474" mmax_level="section"/>
<markable id="markable_40" span="word_475..word_509" mmax_level="section"/>
<markable id="markable_43" span="word_510..word_532" mmax_level="section"/>
<markable id="markable_45" span="word_533..word_548" mmax_level="section"/>
</markables>

=== anastasia-zhukova/uCDCR/NP4E-prep/NP4E/tajikistan/markables/380653newsML_coref_level.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE markables SYSTEM "markables.dtd">
<markables xmlns="www.eml.org/NameSpaces/coref">
<markable id="markable_2" span="word_13" mmax_level="coref" coref_set="set_1"/>
<markable id="markable_3" span="word_17" mmax_level="coref" coref_set="set_0"/>
<markable id="markable_6" span="word_33..word_34" mmax_level="coref" coref_set="set_2"/>
<markable id="markable_8" span="word_36" mmax_level="coref" coref_set="set_0" dir_antecedent="markable_3"/>
<markable id="markable_5" span="word_26..word_39" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2" min_ids="word_26..word_30"/>
<markable id="markable_10" span="word_46" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_9" span="word_46..word_47" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_11" span="word_51" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_12" span="word_53..word_55" mmax_level="coref" coref_set="set_8"/>
<markable id="markable_14" span="word_64..word_66" mmax_level="coref" coref_set="set_11"/>
<markable id="markable_15" span="word_68..word_70" mmax_level="coref" coref_set="set_9"/>
<markable id="markable_18" span="word_79" mmax_level="coref" coref_set="set_18"/>
<markable id="markable_19" span="word_81..word_82" mmax_level="coref" coref_set="set_3"/>
<markable id="markable_17" span="word_78..word_82" mmax_level="coref" coref_set="set_17"/>
<markable id="markable_16" span="word_73..word_82" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6" min_ids="word_73..word_75"/>
<markable id="markable_21" span="word_93..word_94" mmax_level="coref" coref_set="set_3" dir_antecedent="markable_19"/>
<markable id="markable_22" span="word_98..word_99" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_24" span="word_101" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_26" span="word_110..word_113" mmax_level="coref" coref_set="set_4" dir_antecedent="markable_25" min_ids="word_110..word_111"/>
<markable id="markable_25" span="word_107..word_113" mmax_level="coref" coref_set="set_4"/>
<markable id="markable_29" span="word_118" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_28" span="word_118..word_119" mmax_level="coref" coref_set="set_10"/>
<markable id="markable_27" span="word_115..word_119" mmax_level="coref" coref_set="set_5" min_ids="word_115..word_116"/>
<markable id="markable_31" span="word_128" mmax_level="coref" coref_set="set_5" dir_antecedent="markable_27"/>
<markable id="markable_32" span="word_133..word_142" mmax_level="coref" coref_set="set_6"/>
<markable id="markable_37" span="word_156" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_38" span="word_159..word_160" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_39" span="word_162" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_41" span="word_174" mmax_level="coref" coref_set="set_6" dir_antecedent="markable_32"/>
<markable id="markable_44" span="word_180..word_181" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_45" span="word_183" mmax_level="coref" coref_set="set_6" dir_antecedent="markable_32"/>
<markable id="markable_46" span="word_187" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_44"/>
<markable id="markable_47" span="word_197" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_46"/>
<markable id="markable_48" span="word_205" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_46"/>
<markable id="markable_49" span="word_211..word_212" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_54" span="word_239..word_243" mmax_level="coref" coref_set="set_7"/>
<markable id="markable_61" span="word_245" mmax_level="coref" coref_set="set_7" dir_antecedent="markable_54"/>
<markable id="markable_63" span="word_251" mmax_level="coref" coref_set="set_7" dir_antecedent="markable_54"/>
<markable id="markable_66" span="word_265..word_268" mmax_level="coref" coref_set="set_0" dir_antecedent="markable_3"/>
<markable id="markable_67" span="word_271..word_276" mmax_level="coref" coref_set="set_8" dir_antecedent="markable_12" min_ids="word_271..word_272"/>
<markable id="markable_70" span="word_280" mmax_level="coref" coref_set="set_3" dir_antecedent="markable_19"/>
<markable id="markable_69" span="word_278..word_282" mmax_level="coref" coref_set="set_9" dir_antecedent="markable_15" min_ids="word_278"/>
<markable id="markable_72" span="word_287" mmax_level="coref" coref_set="set_13"/>
<markable id="markable_74" span="word_293" mmax_level="coref" coref_set="set_3" dir_antecedent="markable_19"/>
<markable id="markable_73" span="word_293..word_311" mmax_level="coref" coref_set="set_10" dir_antecedent="markable_28" min_ids="word_293..word_296"/>
<markable id="markable_77" span="word_313..word_314" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_79" span="word_320" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_78" span="word_320..word_321" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_172" span="word_325" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_82" span="word_337..word_349" mmax_level="coref" coref_set="set_12" min_ids="word_337..word_338"/>
<markable id="markable_84" span="word_353..word_354" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_86" span="word_358" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_85" span="word_358..word_359" mmax_level="coref" coref_set="set_5" dir_antecedent="markable_27"/>
<markable id="markable_88" span="word_361" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_90" span="word_369..word_371" mmax_level="coref" coref_set="set_11" dir_antecedent="markable_14"/>
<markable id="markable_92" span="word_378" mmax_level="coref" coref_set="set_12" dir_antecedent="markable_82"/>
<markable id="markable_93" span="word_380..word_381" mmax_level="coref" coref_set="set_2" dir_antecedent="markable_6"/>
<markable id="markable_95" span="word_394..word_395" mmax_level="coref" coref_set="set_1" dir_antecedent="markable_2"/>
<markable id="markable_101" span="word_411" mmax_level="coref" coref_set="set_13" dir_antecedent="markable_72"/>
<markable id="markable_98" span="word_404..word_413" mmax_level="coref" coref_set="set_0" dir_antecedent="markable_3"/>
<markable id="markable_104" span="word_415..word_417" mmax_level="coref" coref_set="set_16"/>
<markable id="markable_106" span="word_427..word_429" mmax_level="coref" coref_set="set_14" dir_antecedent="markable_105"/>
<markable id="markable_105" span="word_419..word_429" mmax_level="coref" coref_set="set_14" min_ids="word_419..word_420"/>
<markable id="markable_108" span="word_433..word_434" mmax_level="coref" coref_set="set_15"/>
<markable id="markable_113" span="word_452..word_453" mmax_level="coref" coref_set="set_15" dir_antecedent="markable_108"/>
<markable id="markable_115" span="word_465" mmax_level="coref" coref_set="set_16" dir_antecedent="markable_104"/>
<markable id="markable_116" span="word_470..word_471" mmax_level="coref" coref_set="set_0" dir_antecedent="markable_3"/>
<markable id="markable_119" span="word_479..word_480" mmax_level="coref" coref_set="set_17" dir_antecedent="markable_17"/>
<markable id="markable_120" span="word_485" mmax_level="coref" coref_set="set_13" dir_antecedent="markable_72"/>
<markable id="markable_121" span="word_487..word_501" mmax_level="coref" coref_set="set_18" dir_antecedent="markable_18"/>
<markable id="markable_127" span="word_506" mmax_level="coref" coref_set="set_16" dir_antecedent="markable_104"/>
<markable id="markable_130" span="word_521" mmax_level="coref" coref_set="set_18" dir_antecedent="markable_18"/>
</markables>

=== anastasia-zhukova/uCDCR/NP4E-prep/NP4E/china/markables/431810newsML_sentence_level.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE markables SYSTEM "markables.dtd">
<markables xmlns="www.eml.org/NameSpaces/sentence">
<markable id="markable_1" span="word_1..word_10" mmax_level="sentence"/>
<markable id="markable_3" span="word_11..word_18" mmax_level="sentence"/>
<markable id="markable_5" span="word_19..word_20" mmax_level="sentence"/>
<markable id="markable_7" span="word_21..word_54" mmax_level="sentence"/>
<markable id="markable_9" span="word_55..word_97" mmax_level="sentence"/>
<markable id="markable_11" span="word_98..word_110" mmax_level="sentence"/>
<markable id="markable_13" span="word_111..word_144" mmax_level="sentence"/>
<markable id="markable_15" span="word_145..word_160" mmax_level="sentence"/>
<markable id="markable_17" span="word_161..word_200" mmax_level="sentence"/>
<markable id="markable_19" span="word_201..word_240" mmax_level="sentence"/>
</markables>
